### ISSUE TITLE
ADB Does not exist dialog in Code-OSS (a.k.a VS Code) GNU/Linux 

### ISSUE THREAD

**Issue by Av1nag** [deskbtm/android-adb-wlan#11]
I was trying to connect to my mobile wirelessly for USB debugging. But when I'm trying to connect by clicking the below mentioned button it is arising error dialog even though the adb platform tools are present in the device...

![Screenshot from 2023-10-10 09-25-37](https://github.com/deskbtm/android-adb-wlan/assets/116362503/941389ee-3b35-46cb-8a3e-15fbcb1673e0)

![image](https://github.com/deskbtm/android-adb-wlan/assets/116362503/ea61535f-9f1a-4cd1-908c-1df0731d5a4d)

The path of the platform-tools in `~/.bashrc` are:

`export ANDROID_HOME=$HOME/Android/Sdk`
`export PATH=$PATH:$ANDROID_HOME/platform-tools`

The path of the platform tools aren't detecting by android-abd-wlan. So, I chose an alternative of connecting to wireless device manually by using prompts `abd  pair HOST[:PORT] [PAIRING CODE]` and `abd  connect HOST[:PORT] ` in bash terminal. That works actually, but the extension is not working as expected.. So help me to solve this issue. If you want info I' always free to provide.

Thank you. :heart:

**Comment by han9088** [comment]
I tried CodeOSS on Archlinux but could not reproduce

![image](https://github.com/deskbtm/android-adb-wlan/assets/45007226/419f8aa5-bc17-4c24-9ca5-e17f7c2b64cc)
