### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by KiddyCodes** [deskbtm/android-adb-wlan#7]
- Issue Type: `Performance`
- Extension Name: `android-adb-wlan`
- Extension Version: `0.0.7`
- OS Version: `Windows_NT x64 10.0.18362`
- VS Code version: `1.61.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\PC\AppData\Local\Temp\HanWang.android-adb-wlan-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by han9088** [comment]
Any file to provide?
