### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by jeremyjr18** [deskbtm/android-adb-wlan#9]
- Issue Type: `Bug`
- Extension Name: `android-adb-wlan`
- Extension Version: `0.0.9`
- OS Version: `Windows_NT x64 10.0.22000`
- VS Code version: `1.68.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by han9088** [comment]
@jeremyjr18 This may not be caused by the extension. Plz see https://github.com/microsoft/vscode/issues/114624
